/**
 * tailwind.config.js — ForgeX | Library design system
 * Auto-generated by build-tokens.js from Figma variable reads.
 *
 * COLOR ARCHITECTURE (mirrors the Figma collections)
 * --------------------------------------------------
 * • palette  -> primitive ramps, mode-agnostic, exposed as `palette-<family>-<step>`
 *               (e.g. bg-palette-brand-400). You normally don't use these directly.
 * • theme    -> semantic tokens (base, inverse, tint/*, text/*, main/*). These are
 *               CSS variables that flip with the mode: light on :root, dark on .dark.
 *               Use these in product code: bg-base, text-text-neutral-100,
 *               bg-tint-brand-200, bg-main-brand (=.../base), text-main-warning-contrast.
 *
 * Dark mode is class-based: add `class="dark"` on <html> to switch.
 * The :root / .dark variable values are injected by the plugin at the bottom.
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx,html}'],
  darkMode: 'class',
  theme: {
    // Figma values only — replaces Tailwind's default breakpoints (large-desktop-first).
    screens: {
      min: '1920px', // breakpoint/width/min (= breakpoint/width/default)
      max: '2160px', // breakpoint/width/max
    },

    extend: {
      colors: {
        white: '#ffffff',
        black: '#000000',
        transparent: 'transparent',
        current: 'currentColor',
        base: 'var(--base)',
        inverse: 'var(--inverse)',
        tint: {
          neutral: {
            '50': 'var(--tint-neutral-50)',
            '100': 'var(--tint-neutral-100)',
            '150': 'var(--tint-neutral-150)',
            '200': 'var(--tint-neutral-200)',
            '250': 'var(--tint-neutral-250)',
            '300': 'var(--tint-neutral-300)',
            '400': 'var(--tint-neutral-400)',
            '500': 'var(--tint-neutral-500)',
          },
          brand: {
            '50': 'var(--tint-brand-50)',
            '100': 'var(--tint-brand-100)',
            '150': 'var(--tint-brand-150)',
            '200': 'var(--tint-brand-200)',
            '250': 'var(--tint-brand-250)',
            '300': 'var(--tint-brand-300)',
          },
          accent: {
            '50': 'var(--tint-accent-50)',
            '100': 'var(--tint-accent-100)',
            '150': 'var(--tint-accent-150)',
            '200': 'var(--tint-accent-200)',
            '250': 'var(--tint-accent-250)',
            '300': 'var(--tint-accent-300)',
          },
          info: {
            '50': 'var(--tint-info-50)',
            '100': 'var(--tint-info-100)',
            '150': 'var(--tint-info-150)',
            '200': 'var(--tint-info-200)',
            '250': 'var(--tint-info-250)',
            '300': 'var(--tint-info-300)',
          },
          warning: {
            '50': 'var(--tint-warning-50)',
            '100': 'var(--tint-warning-100)',
            '150': 'var(--tint-warning-150)',
            '200': 'var(--tint-warning-200)',
            '250': 'var(--tint-warning-250)',
            '300': 'var(--tint-warning-300)',
          },
          positive: {
            '50': 'var(--tint-positive-50)',
            '100': 'var(--tint-positive-100)',
            '150': 'var(--tint-positive-150)',
            '200': 'var(--tint-positive-200)',
            '250': 'var(--tint-positive-250)',
            '300': 'var(--tint-positive-300)',
          },
          negative: {
            '50': 'var(--tint-negative-50)',
            '100': 'var(--tint-negative-100)',
            '150': 'var(--tint-negative-150)',
            '200': 'var(--tint-negative-200)',
            '250': 'var(--tint-negative-250)',
            '300': 'var(--tint-negative-300)',
          },
        },
        text: {
          neutral: {
            '100': 'var(--text-neutral-100)',
            '200': 'var(--text-neutral-200)',
            '300': 'var(--text-neutral-300)',
            '400': 'var(--text-neutral-400)',
          },
          brand: {
            l200: 'var(--text-brand-l200)',
            DEFAULT: 'var(--text-brand-base)',
            d200: 'var(--text-brand-d200)',
          },
          accent: {
            l200: 'var(--text-accent-l200)',
            DEFAULT: 'var(--text-accent-base)',
            d200: 'var(--text-accent-d200)',
          },
          info: {
            l200: 'var(--text-info-l200)',
            DEFAULT: 'var(--text-info-base)',
            d200: 'var(--text-info-d200)',
          },
          warning: {
            l200: 'var(--text-warning-l200)',
            DEFAULT: 'var(--text-warning-base)',
            d200: 'var(--text-warning-d200)',
          },
          positive: {
            l200: 'var(--text-positive-l200)',
            DEFAULT: 'var(--text-positive-base)',
            d200: 'var(--text-positive-d200)',
          },
          negative: {
            l200: 'var(--text-negative-l200)',
            DEFAULT: 'var(--text-negative-base)',
            d200: 'var(--text-negative-d200)',
          },
        },
        main: {
          neutral: {
            l200: 'var(--main-neutral-l200)',
            l100: 'var(--main-neutral-l100)',
            DEFAULT: 'var(--main-neutral-base)',
            d100: 'var(--main-neutral-d100)',
            d200: 'var(--main-neutral-d200)',
            contrast: 'var(--main-neutral-contrast)',
          },
          brand: {
            l200: 'var(--main-brand-l200)',
            l100: 'var(--main-brand-l100)',
            DEFAULT: 'var(--main-brand-base)',
            d100: 'var(--main-brand-d100)',
            d200: 'var(--main-brand-d200)',
            contrast: 'var(--main-brand-contrast)',
          },
          accent: {
            l200: 'var(--main-accent-l200)',
            l100: 'var(--main-accent-l100)',
            DEFAULT: 'var(--main-accent-base)',
            d100: 'var(--main-accent-d100)',
            d200: 'var(--main-accent-d200)',
            contrast: 'var(--main-accent-contrast)',
          },
          info: {
            l200: 'var(--main-info-l200)',
            l100: 'var(--main-info-l100)',
            DEFAULT: 'var(--main-info-base)',
            d100: 'var(--main-info-d100)',
            d200: 'var(--main-info-d200)',
            contrast: 'var(--main-info-contrast)',
          },
          warning: {
            l200: 'var(--main-warning-l200)',
            l100: 'var(--main-warning-l100)',
            DEFAULT: 'var(--main-warning-base)',
            d100: 'var(--main-warning-d100)',
            d200: 'var(--main-warning-d200)',
            contrast: 'var(--main-warning-contrast)',
          },
          positive: {
            l200: 'var(--main-positive-l200)',
            l100: 'var(--main-positive-l100)',
            DEFAULT: 'var(--main-positive-base)',
            d100: 'var(--main-positive-d100)',
            d200: 'var(--main-positive-d200)',
            contrast: 'var(--main-positive-contrast)',
          },
          negative: {
            l200: 'var(--main-negative-l200)',
            l100: 'var(--main-negative-l100)',
            DEFAULT: 'var(--main-negative-base)',
            d100: 'var(--main-negative-d100)',
            d200: 'var(--main-negative-d200)',
            contrast: 'var(--main-negative-contrast)',
          },
        },
        palette: {
          neutral: {
            '25': '#f8f8f9',
            '50': '#f1f1f4',
            '75': '#eaeaee',
            '100': '#e4e4e9',
            '150': '#d6d6dd',
            '200': '#c8c8d2',
            '250': '#bbbbc7',
            '300': '#adadbc',
            '400': '#9292a6',
            '500': '#777790',
            '600': '#606075',
            '650': '#555568',
            '700': '#4a4a5a',
            '750': '#3f3f4d',
            '800': '#34343f',
            '850': '#282831',
            '900': '#1d1d24',
            '925': '#18181d',
            '950': '#121216',
            '975': '#0d0d0f',
          },
          brand: {
            '25': '#f7f5ff',
            '50': '#ede9ff',
            '75': '#e3defe',
            '100': '#dad3fd',
            '150': '#c8bef9',
            '200': '#b6aaf5',
            '250': '#a697ef',
            '300': '#9686e8',
            '400': '#7966d8',
            '500': '#5e4ac3',
            '600': '#4e3f9e',
            '650': '#483b89',
            '700': '#413676',
            '750': '#393063',
            '800': '#302952',
            '850': '#272241',
            '900': '#1e1a31',
            '925': '#191629',
            '950': '#141221',
            '975': '#0f0d19',
          },
          accent: {
            '25': '#f2fce8',
            '50': '#ecfbde',
            '75': '#e6f9d3',
            '100': '#e0f7c9',
            '150': '#d4f3b5',
            '200': '#c8eda2',
            '250': '#bbe790',
            '300': '#afe17e',
            '400': '#97d25c',
            '500': '#7fc03d',
            '600': '#669736',
            '650': '#5a8331',
            '700': '#4e702c',
            '750': '#425e26',
            '800': '#354c1f',
            '850': '#293a18',
            '900': '#1d2911',
            '925': '#17200e',
            '950': '#11180a',
            '975': '#0b0f07',
          },
          info: {
            '25': '#effcfd',
            '50': '#e5f9fb',
            '75': '#daf7f9',
            '100': '#d0f4f7',
            '150': '#bceef3',
            '200': '#a8e8ee',
            '250': '#95e2e9',
            '300': '#82dbe3',
            '400': '#5dcdd7',
            '500': '#39bdc9',
            '600': '#2f99a2',
            '650': '#2b868e',
            '700': '#26737a',
            '750': '#216167',
            '800': '#1b4f54',
            '850': '#163e41',
            '900': '#102c2f',
            '925': '#0d2326',
            '950': '#091b1c',
            '975': '#061213',
          },
          warning: {
            '25': '#fff6ed',
            '50': '#fff0e1',
            '75': '#ffead5',
            '100': '#ffe4c8',
            '150': '#ffd7b0',
            '200': '#fecb98',
            '250': '#fdbf81',
            '300': '#fbb36b',
            '400': '#f49a41',
            '500': '#e9821b',
            '600': '#b8691b',
            '650': '#9f5d1b',
            '700': '#86511b',
            '750': '#6f441a',
            '800': '#583818',
            '850': '#432c15',
            '900': '#2f2011',
            '925': '#251a0e',
            '950': '#1c140b',
            '975': '#130d08',
          },
          positive: {
            '25': '#f2fce8',
            '50': '#ecfbde',
            '75': '#e6f9d3',
            '100': '#e0f7c9',
            '150': '#d4f3b5',
            '200': '#c8eda2',
            '250': '#bbe790',
            '300': '#afe17e',
            '400': '#97d25c',
            '500': '#7fc03d',
            '600': '#669736',
            '650': '#5a8331',
            '700': '#4e702c',
            '750': '#425e26',
            '800': '#354c1f',
            '850': '#293a18',
            '900': '#1d2911',
            '925': '#17200e',
            '950': '#11180a',
            '975': '#0b0f07',
          },
          negative: {
            '25': '#fef3f3',
            '50': '#fee7e7',
            '75': '#fddcdc',
            '100': '#fcd1d1',
            '150': '#f9bbbb',
            '200': '#f6a6a6',
            '250': '#f29191',
            '300': '#ed7d7d',
            '400': '#e25757',
            '500': '#d43434',
            '600': '#ac2b2b',
            '650': '#952929',
            '700': '#802626',
            '750': '#6b2222',
            '800': '#571e1e',
            '850': '#431919',
            '900': '#311313',
            '925': '#271010',
            '950': '#1e0d0d',
            '975': '#150909',
          },
        },
      },

      borderRadius: {
        xs: '0.125rem', // 2
        sm: '0.25rem', // 4
        md: '0.5rem', // 8
        lg: '0.75rem', // 12
        xl: '1rem', // 16
        max: '9999px', // pill / fully rounded
      },

      // ForgeX 4px spacing grid (px-named tokens from the Figma number collection).
      // NOTE: these override Tailwind's default spacing for matching keys
      // (e.g. `p-4` becomes 4px, not 16px).
      spacing: {
        0: '0',
        4: '0.25rem', 6: '0.375rem', 8: '0.5rem', 12: '0.75rem', 16: '1rem',
        24: '1.5rem', 28: '1.75rem', 32: '2rem', 40: '2.5rem',
      },

      // Shadows (Figma: shadow/<outer|inner>/<size>/neutral/<intensity>)
      boxShadow: {
        'outer-sm-100': '0px 4px 12px 0px rgba(0, 0, 0, 0.05)',
        'outer-sm-200': '0px 4px 12px 0px rgba(0, 0, 0, 0.10)',
        'outer-sm-300': '0px 4px 12px 0px rgba(0, 0, 0, 0.15)',
        'outer-md-100': '0px 8px 24px 0px rgba(0, 0, 0, 0.05)',
        'outer-md-200': '0px 8px 24px 0px rgba(0, 0, 0, 0.10)',
        'outer-md-300': '0px 8px 24px 0px rgba(0, 0, 0, 0.15)',
        'outer-lg-100': '0px 12px 36px 0px rgba(0, 0, 0, 0.05)',
        'outer-lg-200': '0px 12px 36px 0px rgba(0, 0, 0, 0.10)',
        'outer-lg-300': '0px 12px 36px 0px rgba(0, 0, 0, 0.15)',
        'inner-sm-100': 'inset 0px 2px 2px 0px rgba(0, 0, 0, 0.04)',
        'inner-sm-200': 'inset 0px 2px 2px 0px rgba(0, 0, 0, 0.06)',
        'inner-sm-300': 'inset 0px 2px 2px 0px rgba(0, 0, 0, 0.09)',
        'inner-md-100': 'inset 0px 4px 4px 0px rgba(0, 0, 0, 0.04)',
        'inner-md-200': 'inset 0px 4px 4px 0px rgba(0, 0, 0, 0.06)',
        'inner-md-300': 'inset 0px 4px 4px 0px rgba(0, 0, 0, 0.09)',
        'inner-lg-100': 'inset 0px 8px 8px 0px rgba(0, 0, 0, 0.04)',
        'inner-lg-200': 'inset 0px 8px 8px 0px rgba(0, 0, 0, 0.06)',
        'inner-lg-300': 'inset 0px 8px 8px 0px rgba(0, 0, 0, 0.09)',
      },

      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        inter: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },

      fontWeight: {
        regular: '400', semibold: '600', bold: '700', extrabold: '800', black: '900',
      },

      // Typography — synced from Figma "Typography" frame (node 2086:9499).
      // Naming: <group>-<size>. Headline carries 7 sizes (xxs->xxl); all other
      // groups carry 5 sizes (xs->xl). Comments show pixel pair fontSize/lineHeight.
      fontSize: {
        // display — Inter ExtraBold (800)
        'display-xs': ['1.5rem',  { lineHeight: '2.25rem', letterSpacing: '-0.75px', fontWeight: '800' }], // 24/36
        'display-sm': ['1.75rem', { lineHeight: '2.5rem',  letterSpacing: '-1px',    fontWeight: '800' }], // 28/40
        'display-md': ['2rem',    { lineHeight: '2.75rem', letterSpacing: '-1.25px', fontWeight: '800' }], // 32/44
        'display-lg': ['2.25rem', { lineHeight: '3rem',    letterSpacing: '-1.5px',  fontWeight: '800' }], // 36/48
        'display-xl': ['3rem',    { lineHeight: '3.75rem', letterSpacing: '-2px',    fontWeight: '800' }], // 48/60

        // headline — Inter Bold (700)
        'headline-xxs': ['0.875rem', { lineHeight: '1.125rem', letterSpacing: '0px',      fontWeight: '700' }], // 14/18
        'headline-xs':  ['1rem',     { lineHeight: '1.25rem',  letterSpacing: '0px',      fontWeight: '700' }], // 16/20
        'headline-sm':  ['1.125rem', { lineHeight: '1.375rem', letterSpacing: '-0.5px',   fontWeight: '700' }], // 18/22
        'headline-md':  ['1.25rem',  { lineHeight: '1.5rem',   letterSpacing: '-0.625px', fontWeight: '700' }], // 20/24
        'headline-lg':  ['1.5rem',   { lineHeight: '1.75rem',  letterSpacing: '-0.75px',  fontWeight: '700' }], // 24/28
        'headline-xl':  ['1.75rem',  { lineHeight: '2rem',     letterSpacing: '-0.875px', fontWeight: '700' }], // 28/32
        'headline-xxl': ['2rem',     { lineHeight: '2.25rem',  letterSpacing: '-1px',     fontWeight: '700' }], // 32/36

        // title — Inter SemiBold (600)
        'title-xs': ['0.75rem',  { lineHeight: '1rem',     letterSpacing: '0px', fontWeight: '600' }], // 12/16
        'title-sm': ['0.875rem', { lineHeight: '1.125rem', letterSpacing: '0px', fontWeight: '600' }], // 14/18
        'title-md': ['1rem',     { lineHeight: '1.25rem',  letterSpacing: '0px', fontWeight: '600' }], // 16/20
        'title-lg': ['1.125rem', { lineHeight: '1.375rem', letterSpacing: '0px', fontWeight: '600' }], // 18/22
        'title-xl': ['1.25rem',  { lineHeight: '1.5rem',   letterSpacing: '0px', fontWeight: '600' }], // 20/24

        // label — Inter SemiBold (600)
        'label-xs': ['0.75rem',  { lineHeight: '1.125rem', letterSpacing: '-0.25px', fontWeight: '600' }], // 12/18
        'label-sm': ['0.875rem', { lineHeight: '1.25rem',  letterSpacing: '-0.25px', fontWeight: '600' }], // 14/20
        'label-md': ['1rem',     { lineHeight: '1.375rem', letterSpacing: '-0.25px', fontWeight: '600' }], // 16/22
        'label-lg': ['1.125rem', { lineHeight: '1.5rem',   letterSpacing: '-0.25px', fontWeight: '600' }], // 18/24
        'label-xl': ['1.25rem',  { lineHeight: '1.75rem',  letterSpacing: '-0.25px', fontWeight: '600' }], // 20/28

        // button — Inter Black (900)
        'button-xxs': ['0.75rem',  { lineHeight: '1.125rem', letterSpacing: '0px', fontWeight: '900' }], // 12/18
        'button-xs':  ['0.875rem', { lineHeight: '1.375rem', letterSpacing: '0px', fontWeight: '900' }], // 14/22
        'button-sm':  ['1rem',     { lineHeight: '1.375rem', letterSpacing: '0px', fontWeight: '900' }], // 16/22
        'button-md':  ['1.25rem',  { lineHeight: '1.5rem',   letterSpacing: '0px', fontWeight: '900' }], // 20/24
        'button-lg':  ['1.75rem',  { lineHeight: '2rem',     letterSpacing: '0px', fontWeight: '900' }], // 28/32

        // body — Inter Regular (400)
        'body-xs': ['0.75rem',  { lineHeight: '1.125rem', letterSpacing: '-0.25px', fontWeight: '400' }], // 12/18
        'body-sm': ['0.875rem', { lineHeight: '1.25rem',  letterSpacing: '-0.25px', fontWeight: '400' }], // 14/20
        'body-md': ['1rem',     { lineHeight: '1.375rem', letterSpacing: '-0.25px', fontWeight: '400' }], // 16/22
        'body-lg': ['1.125rem', { lineHeight: '1.5rem',   letterSpacing: '-0.25px', fontWeight: '400' }], // 18/24
        'body-xl': ['1.25rem',  { lineHeight: '1.75rem',  letterSpacing: '-0.25px', fontWeight: '400' }], // 20/28

        // bodyStrong — Inter Bold (700)
        'body-strong-xs': ['0.75rem',  { lineHeight: '1.125rem', letterSpacing: '-0.25px', fontWeight: '700' }], // 12/18
        'body-strong-sm': ['0.875rem', { lineHeight: '1.25rem',  letterSpacing: '-0.25px', fontWeight: '700' }], // 14/20
        'body-strong-md': ['1rem',     { lineHeight: '1.375rem', letterSpacing: '-0.25px', fontWeight: '700' }], // 16/22
        'body-strong-lg': ['1.125rem', { lineHeight: '1.5rem',   letterSpacing: '-0.25px', fontWeight: '700' }], // 18/24
        'body-strong-xl': ['1.25rem',  { lineHeight: '1.75rem',  letterSpacing: '-0.25px', fontWeight: '700' }], // 20/28
      },
    },
  },
  plugins: [
    // Injects theme token values. Light on :root, dark under .dark.
    function ({ addBase }) {
      addBase({
        ':root': {
            '--base': '#ffffff',
            '--inverse': '#000000',
            '--tint-neutral-50': '#f1f1f4',
            '--tint-neutral-100': '#e4e4e9',
            '--tint-neutral-150': '#d6d6dd',
            '--tint-neutral-200': '#c8c8d2',
            '--tint-neutral-250': '#bbbbc7',
            '--tint-neutral-300': '#adadbc',
            '--tint-neutral-400': '#9292a6',
            '--tint-neutral-500': '#777790',
            '--tint-brand-50': '#ede9ff',
            '--tint-brand-100': '#dad3fd',
            '--tint-brand-150': '#c8bef9',
            '--tint-brand-200': '#b6aaf5',
            '--tint-brand-250': '#a697ef',
            '--tint-brand-300': '#9686e8',
            '--tint-accent-50': '#ecfbde',
            '--tint-accent-100': '#e0f7c9',
            '--tint-accent-150': '#d4f3b5',
            '--tint-accent-200': '#c8eda2',
            '--tint-accent-250': '#bbe790',
            '--tint-accent-300': '#afe17e',
            '--tint-info-50': '#e5f9fb',
            '--tint-info-100': '#d0f4f7',
            '--tint-info-150': '#bceef3',
            '--tint-info-200': '#a8e8ee',
            '--tint-info-250': '#95e2e9',
            '--tint-info-300': '#82dbe3',
            '--tint-warning-50': '#fff0e1',
            '--tint-warning-100': '#ffe4c8',
            '--tint-warning-150': '#ffd7b0',
            '--tint-warning-200': '#fecb98',
            '--tint-warning-250': '#fdbf81',
            '--tint-warning-300': '#fbb36b',
            '--tint-positive-50': '#ecfbde',
            '--tint-positive-100': '#e0f7c9',
            '--tint-positive-150': '#d4f3b5',
            '--tint-positive-200': '#c8eda2',
            '--tint-positive-250': '#bbe790',
            '--tint-positive-300': '#afe17e',
            '--tint-negative-50': '#fee7e7',
            '--tint-negative-100': '#fcd1d1',
            '--tint-negative-150': '#f9bbbb',
            '--tint-negative-200': '#f6a6a6',
            '--tint-negative-250': '#f29191',
            '--tint-negative-300': '#ed7d7d',
            '--text-neutral-100': '#000000',
            '--text-neutral-200': '#3f3f4d',
            '--text-neutral-300': '#777790',
            '--text-neutral-400': '#bbbbc7',
            '--text-brand-l200': '#b6aaf5',
            '--text-brand-base': '#7966d8',
            '--text-brand-d200': '#5441b4',
            '--text-accent-l200': '#a3da6d',
            '--text-accent-base': '#72ab3a',
            '--text-accent-d200': '#425e26',
            '--text-info-l200': '#6fd4dd',
            '--text-info-base': '#34acb7',
            '--text-info-d200': '#216167',
            '--text-warning-l200': '#fbb36b',
            '--text-warning-base': '#e9821b',
            '--text-warning-d200': '#86511b',
            '--text-positive-l200': '#afe17e',
            '--text-positive-base': '#7fc03d',
            '--text-positive-d200': '#4e702c',
            '--text-negative-l200': '#ed7d7d',
            '--text-negative-base': '#d43434',
            '--text-negative-d200': '#802626',
            '--main-neutral-l200': '#adadbc',
            '--main-neutral-l100': '#9292a6',
            '--main-neutral-base': '#777790',
            '--main-neutral-d100': '#606075',
            '--main-neutral-d200': '#4a4a5a',
            '--main-neutral-contrast': '#ffffff',
            '--main-brand-l200': '#a697ef',
            '--main-brand-l100': '#8775e1',
            '--main-brand-base': '#6b57ce',
            '--main-brand-d100': '#5441b4',
            '--main-brand-d200': '#483b89',
            '--main-brand-contrast': '#ffffff',
            '--main-accent-l200': '#afe17e',
            '--main-accent-l100': '#97d25c',
            '--main-accent-base': '#7fc03d',
            '--main-accent-d100': '#669736',
            '--main-accent-d200': '#4e702c',
            '--main-accent-contrast': '#ffffff',
            '--main-info-l200': '#82dbe3',
            '--main-info-l100': '#5dcdd7',
            '--main-info-base': '#39bdc9',
            '--main-info-d100': '#2f99a2',
            '--main-info-d200': '#26737a',
            '--main-info-contrast': '#000000',
            '--main-warning-l200': '#fec58d',
            '--main-warning-l100': '#f9ad60',
            '--main-warning-base': '#f19437',
            '--main-warning-d100': '#df7c18',
            '--main-warning-d200': '#ab631b',
            '--main-warning-contrast': '#ffffff',
            '--main-positive-l200': '#afe17e',
            '--main-positive-l100': '#97d25c',
            '--main-positive-base': '#7fc03d',
            '--main-positive-d100': '#669736',
            '--main-positive-d200': '#4e702c',
            '--main-positive-contrast': '#ffffff',
            '--main-negative-l200': '#ed7d7d',
            '--main-negative-l100': '#e25757',
            '--main-negative-base': '#d43434',
            '--main-negative-d100': '#ac2b2b',
            '--main-negative-d200': '#802626',
            '--main-negative-contrast': '#ffffff',
        },
        '.dark': {
            '--base': '#1d1d24',
            '--inverse': '#ffffff',
            '--tint-neutral-50': '#282831',
            '--tint-neutral-100': '#34343f',
            '--tint-neutral-150': '#3f3f4d',
            '--tint-neutral-200': '#4a4a5a',
            '--tint-neutral-250': '#555568',
            '--tint-neutral-300': '#606075',
            '--tint-neutral-400': '#777790',
            '--tint-neutral-500': '#9292a6',
            '--tint-brand-50': '#272241',
            '--tint-brand-100': '#302952',
            '--tint-brand-150': '#393063',
            '--tint-brand-200': '#413676',
            '--tint-brand-250': '#483b89',
            '--tint-brand-300': '#4e3f9e',
            '--tint-accent-50': '#293a18',
            '--tint-accent-100': '#354c1f',
            '--tint-accent-150': '#425e26',
            '--tint-accent-200': '#4e702c',
            '--tint-accent-250': '#5a8331',
            '--tint-accent-300': '#669736',
            '--tint-info-50': '#163e41',
            '--tint-info-100': '#1b4f54',
            '--tint-info-150': '#216167',
            '--tint-info-200': '#26737a',
            '--tint-info-250': '#2b868e',
            '--tint-info-300': '#2f99a2',
            '--tint-warning-50': '#432c15',
            '--tint-warning-100': '#583818',
            '--tint-warning-150': '#6f441a',
            '--tint-warning-200': '#86511b',
            '--tint-warning-250': '#9f5d1b',
            '--tint-warning-300': '#b8691b',
            '--tint-positive-50': '#293a18',
            '--tint-positive-100': '#354c1f',
            '--tint-positive-150': '#425e26',
            '--tint-positive-200': '#4e702c',
            '--tint-positive-250': '#5a8331',
            '--tint-positive-300': '#669736',
            '--tint-negative-50': '#431919',
            '--tint-negative-100': '#571e1e',
            '--tint-negative-150': '#6b2222',
            '--tint-negative-200': '#802626',
            '--tint-negative-250': '#952929',
            '--tint-negative-300': '#ac2b2b',
            '--text-neutral-100': '#ffffff',
            '--text-neutral-200': '#c8c8d2',
            '--text-neutral-300': '#9292a6',
            '--text-neutral-400': '#606075',
            '--text-brand-l200': '#c8bef9',
            '--text-brand-base': '#8775e1',
            '--text-brand-d200': '#5441b4',
            '--text-accent-l200': '#a3da6d',
            '--text-accent-base': '#72ab3a',
            '--text-accent-d200': '#425e26',
            '--text-info-l200': '#6fd4dd',
            '--text-info-base': '#34acb7',
            '--text-info-d200': '#216167',
            '--text-warning-l200': '#fbb36b',
            '--text-warning-base': '#e9821b',
            '--text-warning-d200': '#86511b',
            '--text-positive-l200': '#afe17e',
            '--text-positive-base': '#7fc03d',
            '--text-positive-d200': '#4e702c',
            '--text-negative-l200': '#ed7d7d',
            '--text-negative-base': '#d43434',
            '--text-negative-d200': '#802626',
            '--main-neutral-l200': '#adadbc',
            '--main-neutral-l100': '#9292a6',
            '--main-neutral-base': '#777790',
            '--main-neutral-d100': '#606075',
            '--main-neutral-d200': '#4a4a5a',
            '--main-neutral-contrast': '#ffffff',
            '--main-brand-l200': '#a697ef',
            '--main-brand-l100': '#8775e1',
            '--main-brand-base': '#6b57ce',
            '--main-brand-d100': '#5441b4',
            '--main-brand-d200': '#483b89',
            '--main-brand-contrast': '#ffffff',
            '--main-accent-l200': '#afe17e',
            '--main-accent-l100': '#97d25c',
            '--main-accent-base': '#7fc03d',
            '--main-accent-d100': '#669736',
            '--main-accent-d200': '#4e702c',
            '--main-accent-contrast': '#ffffff',
            '--main-info-l200': '#82dbe3',
            '--main-info-l100': '#5dcdd7',
            '--main-info-base': '#39bdc9',
            '--main-info-d100': '#2f99a2',
            '--main-info-d200': '#26737a',
            '--main-info-contrast': '#000000',
            '--main-warning-l200': '#fecb98',
            '--main-warning-l100': '#fbb36b',
            '--main-warning-base': '#f49a41',
            '--main-warning-d100': '#e9821b',
            '--main-warning-d200': '#b8691b',
            '--main-warning-contrast': '#000000',
            '--main-positive-l200': '#afe17e',
            '--main-positive-l100': '#97d25c',
            '--main-positive-base': '#7fc03d',
            '--main-positive-d100': '#669736',
            '--main-positive-d200': '#4e702c',
            '--main-positive-contrast': '#ffffff',
            '--main-negative-l200': '#ed7d7d',
            '--main-negative-l100': '#e25757',
            '--main-negative-base': '#d43434',
            '--main-negative-d100': '#ac2b2b',
            '--main-negative-d200': '#802626',
            '--main-negative-contrast': '#ffffff',
        },
      });
    },
  ],
};
